language: python
python:
  - "2.7"

sudo: false

env:
  global:
    - AWS_DEFAULT_REGION=eu-west-1
    - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH

install:
  - pip install pytest

script:
  - test.py

install: true

deploy:
  file: "alexa-christmas-countdown.py"
  provider: lambda
  function_name: "AlexaChristmasCountdown"
  region: "eu-west-1"
  publish: false
